name: Build on PR
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Out Secret
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: |
          ./gradlew build