name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew buildDeployWar

      - name: Deploy to Tomcat
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/libs/attendanceApi.war"
          target: "/opt/tomcat/webapps/"
          strip_components: 2

      - name: Set File Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod 770 /opt/tomcat/webapps/attendanceApi.war

      - name: Reload Tomcat Webapp
        run: |
          curl --user ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} "${{ secrets.TOMCAT_SERVER_URL }}/manager/text/reload?path=${{ secrets.TOMCAT_APP_PATH }}"
